---
title: "PopolazioneDatabase"
author: "Daniele Passabì"
date: "6/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# CONNESSIONE AD UNA BASE DI DATI

# Prima di tutto, installo il pacchetto RPostgreSQL
# install.packages("RPostgreSQL")

# Ora ne carico la libreria
library("RPostgreSQL")

# Carico il driver PostgreSQL (e lo memorizzo in una variabile)
drv = dbDriver("PostgreSQL")

# Ora creo la connessione, memorizzata anch'essa in una variabile

dbname = "zoo"
host = "127.0.0.1"
port = 5432
user = "postgres"
password_dany = "dany1998"
password_mansi = "nvidia"

con = dbConnect(drv,
                dbname=dbname,
                host=host,
                port=port,             # usually 5432
                user=user,
                password=password_dany
                )

# Controllo che la connessione si sia stabilita in modo corretto
dbListTables(con)   # --> character(0) se non ci sono Table nel nostro DB

```

```{r}

# AREA

# Nome delle aree
area.nome = c()

for ( i in 1:10 ){
  area.nome[i] = paste("Area", as.character(i))
}

# Numero di abitazioni (inizialmente un vettore di 0 lungo 10)
area.numero_abitazioni = rep(0, 10)

# Creo il DF (che userò poi per la Table su Postgre)
area_df = data.frame(nome = area.nome,
                     numero_abitazioni = area.numero_abitazioni)

# Popolo il database, aggiungendo le aree
dbWriteTable(
              con,
              name=c("public","area"),
              value=area_df,
              append = TRUE,
              row.names=FALSE
              )

```

```{r}

# ANIMALI

genere.nome = readLines("animali.txt")
length(genere.nome) # 80 animali

genere_df = data.frame(nome = genere.nome)
head(genere_df)

# Popolo il database, aggiungendo i generi di animali
dbWriteTable(
              con,
              name=c("public","genere"),
              value=genere_df,
              append = TRUE,
              row.names=FALSE
              )

```

```{r}

# ABITAZIONI

# id (=nome), genere, numero_gabbie, area

# Creo un vettore con 100 id di abitazioni
abitazione.nome = c()

for ( i in 1:100 ){
  abitazione.nome[i] = 1110000 + i     # per convenzione le abitazioni iniziano con '111'
}

# Numero gabbie (vettore di 0 lungo 100)
abitazione.numero_gabbie = rep(0, 100)

# Ottengo i generi
vettore_genere = dbGetQuery(con, "select nome from genere")   # query sul db
vettore_genere = vettore_genere$nome

# Ottengo le aree
vettore_area = dbGetQuery(con, "select nome from area")       # query sul db
vettore_area = vettore_area$nome

# Creo il DF (che userò poi per la Table su Postgre)
abitazione_df = data.frame(
                            id = abitazione.nome,
                            numero_gabbie = abitazione.numero_gabbie,
                            genere = sample(vettore_genere, 100, replace = TRUE),
                            area = sample(vettore_area, 100, replace = TRUE)
                          )

# Popolo il database, aggiungendo le abitazioni
dbWriteTable(
              con,
              name=c("public","abitazione"),
              value=abitazione_df,
              append = TRUE,
              row.names=FALSE
              )


```

```{r}

# GABBIA ed ESEMPLARE

# Idea alla base

# 1. Creo 50 gabbie per ogni abitazione (numero totale abitazioni = 100)
# 2. Itero su ogni abitazione, poi su ogni gabbia, e creo 50 istanze di animali di quel tipo

# GABBIA

# Creo un vettore con 10*100=1000 id di gabbie
gabbia.id = c()

for ( i in 1:5000 ){
  gabbia.id[i] = 2220000 + i    # per convenzione le gabbie iniziano con '222'
}

# Ora devo assegnare casualmente 50 gabbie ad ogni abitazione
vettore_abitazioni = dbGetQuery(con, "select id from abitazione")   # query sul db
vettore_abitazioni = vettore_abitazioni$id

gabbia.abitazione = sample(rep(vettore_abitazioni, 50)) # NB: sample serve a mischiare gli elementi del vettore

# Controllo sulla lunghezza (deve essere 1000)
length(gabbia.id)
length(gabbia.abitazione)

# Creo il DF
gabbia_df = data.frame(
                        id = gabbia.id,
                        abitazione = gabbia.abitazione
                        )

head(gabbia_df)

# Popolo il DB
dbWriteTable(
              con,
              name=c("public","gabbia"),
              value=gabbia_df,
              append = TRUE,
              row.names=FALSE
              )

```

```{r}

# GABBIA ed ESEMPLARE

# Idea alla base

# 1. Creo 50 gabbie per ogni abitazione (numero totale abitazioni = 100)
# 2. Itero su ogni gabbia, trovo il genere dell'abitazione a cui è assegnata e creo un esemplare del genere corretto

# ESEMPLARE

# Ottengo la coppia (gabbia, abitazione)
# Ottengo la coppia (abitazione, genere)
# Ricavo la coppia (gabbia, genere)

# Per farlo basta un join ed una selezione
# SELECT gabbia.id, abitazione.genere
# FROM gabbia JOIN abitazione ON abitazione.id = gabbia.abitazione

vettore_gabbia_genere = dbGetQuery(
                                    con, 
                                    "SELECT gabbia.id, abitazione.genere FROM gabbia JOIN abitazione ON abitazione.id = gabbia.abitazione"
                                   )
# vettore_gabbia_genere

# Creo l'animale in modo corretto, il quale ha bisogno di:
# [X] id                  [333...]
# [X] genere              [DEVE essere lo stesso della gabbia in cui viene contenuto]
# [X] nome                [nomi_animali.txt]
# [X] sesso               [generato casualmente (non è influente)]
# [X] paese_provenienza   [paesi.txt]
# [X] data_nascita        [generare casualmente]
# [X] data_arrivo         [data_nascita + data casuale]
# [X] gabbia              [presente in vettore_gabbia_genere]

# Creo un vettore con 4500 id di esemplare
esemplare.id = c()

for ( i in 1:4500 ){
  esemplare.id[i] = 3330000 + i    # per convenzione gli esemplari (id) iniziano con '333'
}

# Creo un vettore per il nome dell'esemplare con 4500 nomi di animali presi casualmente da 247 nomi di animali
vettore_nomi_animali = readLines("nomi_animali.txt")
esemplare.nome = sample(vettore_nomi_animali, 4500, replace = TRUE)

# Creo un vettore per il sesso dell'esemplare lungo 4500
vettore_sesso = c("M","F")
esemplare.sesso = sample(vettore_sesso, 4500, replace = TRUE)

# Creo un vettore per il paese di provenienza dell'esemplare lungo 4500
vettore_provenienza = readLines("paesi.txt")
esemplare.provenienza = sample(vettore_provenienza, 4500, replace = TRUE)

# Creo un vettore per la data di nascita dell'esemplare con 4500 date casuali
esemplare.data_nascita = sample(seq(as.Date('2010/01/01'), as.Date('2020/01/01'), by="day"), 4500, replace=TRUE)

# Creo un vettore per la data di arrivo dell'esemplare date successive randomiche a quelle di nascita
vettore_giorni = 1:160 # circa 6 mesi
vettore_da_sommare = sample(vettore_giorni, 4500, replace = TRUE)
esemplare.data_arrivo = esemplare.data_nascita + vettore_da_sommare

# Ottengo il vettore con la gabbia
esemplare.gabbia = vettore_gabbia_genere$id[1:4500]

# Ottengo il vettore con il genere
esemplare.genere = vettore_gabbia_genere$genere[1:4500]

# Creo il DF
esemplare_df = data.frame(
                          id = esemplare.id,
                          genere = esemplare.genere,
                          nome = esemplare.nome,
                          sesso = esemplare.sesso,
                          paese_provenienza = esemplare.provenienza,
                          data_nascita = esemplare.data_nascita,
                          data_arrivo = esemplare.data_arrivo,
                          gabbia = esemplare.gabbia
                        )

head(esemplare_df)

# Popolo il DB
dbWriteTable(
              con,
              name=c("public","esemplare"),
              value=esemplare_df,
              append = TRUE,
              row.names=FALSE
              )

```

```{r}

# ADDETTO PULIZIE

library(randomNames)

# Nome
addetto_pulizie.nome = randomNames(
                                    100,
                                    which.names="first"
                                  )

# Cognome
addetto_pulizie.cognome = randomNames(
                                    100,
                                    which.names="last"
                                  )
# CF
id = 4440000
indice = 1
addetto_pulizie.cf = c()

for ( n in addetto_pulizie.nome ){
  
  parte_numerica = id + 1     # per convenzione i CF iniziano con '444'
  id = id + 1
  
  parte_letterale = toupper(substr(n, 1, 3))
  CF = paste(parte_numerica, parte_letterale, sep="")
  
  addetto_pulizie.cf[indice] = CF
  indice = indice + 1
}

# Stipendio
vettore_stipendio_base = rep(1200, 100)
vettore_stipendio_agg = 0:500
vettore_da_sommare = sample(vettore_stipendio_agg, 100, replace = TRUE)
addetto_pulizie.stipendio = vettore_stipendio_base + vettore_da_sommare

# Telefono
vettore_telefono_prefisso = rep(345000000, 100)
vettore_telefono_random = 1:999999
addetto_pulizie.telefono = vettore_telefono_prefisso + sample(vettore_telefono_random, 100, replace = FALSE)

# Turno Pulizia
giorno_inizio = c("Lunedi", "Martedi", "Mercoledi")
giorno_fine = c("Giovedi", "Venerdi")
ora_inizio = c("08:00","09:00","10:00")
ora_fine = c("15:00","16:00","17:00","18:00")

addetto_pulizie.turno_pulizia = c()

for ( i in 1:100 ){
  p1 = sample(giorno_inizio, 1)
  p2 = sample(giorno_fine, 1)
  p3 = sample(ora_inizio, 1)
  p4 = sample(ora_fine, 1)
  
  temp_turno = paste(p1,"-",p2, " ", p3,"-",p4, sep="")
  addetto_pulizie.turno_pulizia[i] = temp_turno
}

# Creo il DF
addetto_pulizie_df = data.frame(
                                cf = addetto_pulizie.cf,
                                nome = addetto_pulizie.nome,
                                cognome = addetto_pulizie.cognome,
                                stipendio = addetto_pulizie.stipendio,
                                telefono = addetto_pulizie.telefono,
                                turno_pulizia = addetto_pulizie.turno_pulizia
                                )
head(addetto_pulizie_df)

# Popolo il DB
dbWriteTable(
              con,
              name=c("public","addetto_pulizie"),
              value=addetto_pulizie_df,
              append = TRUE,
              row.names=FALSE
              )

```

```{r}

# PULIRE

# NB: in media, ad ogni addetto sono assegnate 3 abitazioni

# Addetto pulizie
vettore_addetto_pulizie = dbGetQuery(con, "select cf from addetto_pulizie")
vettore_addetto_pulizie = vettore_addetto_pulizie$cf
pulire.addetto_pulizie = rep(vettore_addetto_pulizie, 3)

# Abitazione
vettore_abitazione = dbGetQuery(con, "select id from abitazione")
pulire.abitazione = sample(rep(vettore_abitazione$id), 3) # randomizzo l'ordine

# Creo il DF
pulire_df = data.frame(
                        addetto_pulizie = pulire.addetto_pulizie,
                        abitazione = pulire.abitazione
                      )

head(pulire_df)

# Popolo il DB
dbWriteTable(
              con,
              name=c("public","pulire"),
              value=pulire_df,
              append = TRUE,
              row.names=FALSE
              )

```

```{r}

# VETERINARIO

# Nome
veterinario.nome = randomNames(
                                20,
                                which.names="first"
                              )

# Cognome
veterinario.cognome = randomNames(
                                   20,
                                   which.names="last"
                                 )
# CF
id = 4440100
indice = 1
veterinario.cf = c()

for ( n in veterinario.nome ){
  
  parte_numerica = id + 1     # per convenzione i CF iniziano con '444'
  id = id + 1
  
  parte_letterale = toupper(substr(n, 1, 3))
  CF = paste(parte_numerica, parte_letterale, sep="")
  
  veterinario.cf[indice] = CF
  indice = indice + 1
}

# Stipendio
vettore_stipendio_base = rep(2000, 20)
vettore_stipendio_agg = 0:600
vettore_da_sommare = sample(vettore_stipendio_agg, 20, replace = TRUE)
veterinario.stipendio = vettore_stipendio_base + vettore_da_sommare

# Telefono
vettore_telefono_prefisso = rep(348000000, 20)
vettore_telefono_random = 1:999999
veterinario.telefono = vettore_telefono_prefisso + sample(vettore_telefono_random, 20, replace = FALSE)

# Creo il DF
veterinario_df = data.frame(
                            cf = veterinario.cf,
                            nome = veterinario.nome,
                            cognome = veterinario.cognome,
                            stipendio = veterinario.stipendio,
                            telefono = veterinario.telefono
                            )
head(veterinario_df)

# Popolo il DB
dbWriteTable(
              con,
              name=c("public","veterinario"),
              value=veterinario_df,
              append = TRUE,
              row.names=FALSE
              )

```

```{r}

# VISITA

# Nota: supponendo di essere a 10 anni dal lancio dell'app, le date delle visite devono essere congruenti

# Serve:
# - veterinario (CF)
# - esemplare (ID)
# - esemplare (genere)
# - data (NB: > data arrivo esemplare nello zoo)
# - peso
# - diagnostica
# - dieta

# INIZIO PROCEDURA

# esemplare ID, genere e data_arrivo
vettore_esemplare = dbGetQuery(con, "select id,genere,data_arrivo from esemplare")

# Preparo gli array vuoti
visita.esemplare_id = c()
visita.esemplare_genere = c()
visita.data = c()

idx = 1

# servono 60 date idonee per ogni esemplare, quindi almeno 60 giorni di scarto tra l'ultima data di arrivo possibile e data_max (considerando il caso peggiore)
data_max = as.Date('2020/12/31') # da mettere 2020 nella versione definitiva

# itero su ogni esemplare
for (index in 1:4500) {
  
  # trovo la data di arrivo dell'esemplare
  data_arrivo = vettore_esemplare$data_arrivo[index]
  
  # ottengo le 60 date idonee (60 * 4500 = 270000 visite previste dalla tabella dei volumi)
  giorni = as.numeric(data_max - data_arrivo, units="days")
  giorni_da_sommare = sample(1:giorni, 60, replace=FALSE)  # FALSE perchè le date *devono* essere diverse --> la data potrebbe essere l'unico attributo che distingue due chiavi uguali!
  
  # Aggiorno i 3 vettori
  for (i in 1:60) {
    visita.esemplare_id[idx] = vettore_esemplare$id[index]
    visita.esemplare_genere[idx] = vettore_esemplare$genere[index]
    visita.data[idx] = as.character(data_arrivo + giorni_da_sommare[i]) # DEVO convertire in stringa per non perdere il valore della data (R converte in intero se la si aggiunge ad una lista)
    idx = idx + 1
  }
}


# Ottengo gli altri vettori necessari alla popolazione del db

# veterinario
vettore_veterinario = dbGetQuery(con, "select cf from veterinario")
vettore_veterinario = vettore_veterinario$cf
visita.veterinario = sample(vettore_veterinario, 270000, replace = TRUE)
length(visita.veterinario)

# peso
visita.peso = sample(1:1200, 270000, replace = TRUE)

# diagnostica
vettore_diagnostica = c(
  "Animale in ottima salute", 
  "Animale in buona salute", 
  "Animale da monitorare, non in pericolo di vita",
  "Animale in pericolo di vita"
  )

visita.diagnostica = sample(vettore_diagnostica, 270000, replace = TRUE)

# dieta
vettore_dieta = c(
  "Quantita di cibo assunta dall'animale ottimale", 
  "Quantita di cibo assunta dall'animale eccessiva, ridurre le dosi", 
  "Quantita di cibo assunta dall'animale non sufficiente, aumentare le dosi"
  )

visita.dieta = sample(vettore_dieta, 270000, replace = TRUE)

# Creo il DF
visita_df = data.frame(
                        veterinario = visita.veterinario,
                        esemplare_id = visita.esemplare_id,
                        esemplare_gen = visita.esemplare_genere,
                        data = as.Date(visita.data), # converto nuovamente in date
                        peso = visita.peso,
                        diagnostica = visita.diagnostica,
                        dieta = visita.dieta
                        )
head(visita_df)

# Popolo il DB
dbWriteTable(
              con,
              name=c("public","visita"),
              value=visita_df,
              append = TRUE,
              row.names=FALSE
              )

```

```{r}

# Disconnessione DB
dbDisconnect(con)

```

























